# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(choices=[(datetime.time(8, 0), '8 AM'), (datetime.time(9, 0), '9 AM'), (datetime.time(10, 0), '10 AM'), (datetime.time(11, 0), '11 AM'), (datetime.time(12, 0), '12 AM'), (datetime.time(13, 0), '1 PM'), (datetime.time(14, 0), '2 PM'), (datetime.time(15, 0), '3 PM'), (datetime.time(16, 0), '4 PM'), (datetime.time(17, 0), '5 PM'), (datetime.time(18, 0), '6 PM'), (datetime.time(19, 0), '7 PM')]),
        ),
    ]
