# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalPractice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='practice',
            field=models.CharField(default='sandyford', max_length=50),
            preserve_default=False,
        ),
    ]
