# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalPractice', '0002_doctor_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='practice',
            field=models.CharField(default='independent', max_length=50),
        ),
    ]
