# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalPractice', '0002_auto_20171201_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalpractice',
            name='image',
        ),
    ]
