# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalPractice', '0003_auto_20171129_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(default='', max_length=254),
        ),
    ]
