# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:50
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medicalPractice', '0004_doctor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
