# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalPractice', '0004_auto_20171206_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(default='dublin', max_length=100),
            preserve_default=False,
        ),
    ]
