# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalPractice', '0005_doctor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalpractice',
            name='location',
            field=models.CharField(default='dublin 9', max_length=100),
            preserve_default=False,
        ),
    ]
